export const actionType = {
  FOOD_LOADED_ADMIN: 'FOOD_LOADED_ADMIN',
  ADD_FOOD_ADMIN: 'ADD_FOOD_ADMIN',
  EDIT_FOOD_ADMIN: 'EDIT_FOOD_ADMIN',
  FILTER_FOODS_ADMIN: 'FILTER_FOODS_ADMIN',
  DELETE_FOOD_ADMIN: 'DELETE_FOOD_ADMIN'

};
